version: '3.1'
services:
  add:
    container_name: youbooking
    image: springboot-youbooking
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service
  postgres-service:
    image: postgres
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=youbooking2
#      POSTGRES_DB: pg_db
#      POSTGRES_PASSWORD: appdbpassword
#    volumes:
#      - /var/lib/postgres
#      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
#
#  message-server:
#    container_name: message-server
#    build:
#      context: docker-message-server
#      dockerfile: Dockerfile
#    image: message-server:latest
#    ports:
#      - 18888:8080
#    networks:
#      - spring-cloud-network
#  product-server:
#    container_name: product-server
#    build:
#      context: docker-product-server
#      dockerfile: Dockerfile
#    image: product-server:latest
#    ports:
#      - 19999:9999
#    networks:
#      - spring-cloud-network
#networks:
#  spring-cloud-network:
#    driver: bridge